# Generated by Django 5.1.1 on 2024-09-10 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_alter_passenger_flight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='flight',
            new_name='flights',
        ),
    ]
